## 1. NumPy ufuncs

In [10]:
# Add element of two list

arr1 = [1,2,3,4]
arr2 = [5,6,7,8]
new_arr = []

for i,j in zip(arr1,arr2):
  new_arr.append(i+j)

print(new_arr)



[6, 8, 10, 12]


In [3]:
#NumPy add()

import numpy as np

arr1 = [1,2,3,4]
arr2 = [5,6,7,8]
new_arr= np.add(arr1,arr2)

print(new_arr)

[ 6  8 10 12]


## 2. Create ufunc

In [ ]:
import numpy as np

def myadd(arr1,arr2):
  return arr1+arr2

my_add = np.frompyfunc(myadd,2,1)

print(myadd([1,2,3,4],[5,6,7,8]))

[1, 2, 3, 4, 5, 6, 7, 8]


In [22]:
#check unfunc

print(type(np.add))

<class 'numpy.ufunc'>


In [15]:
#Check concatenate

import numpy as np

print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [19]:
#checkin ufunc using if statement
import numpy as np

if type(np.add) == (np.ufunc):
  print("Add is ufunc")
else:
  print("Add is not ufunc")

Add is ufunc


In [20]:
np.ufunc

numpy.ufunc

## 3. Simple arithmetic

#### Division

In [23]:
import numpy as np

arr1 = np.array([10,20,30,40,50,60])
arr2  = np.array([3,5,10,8,2,33])

new_arr = np.divide(arr1,arr2)

print(new_arr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


#### Power

In [24]:
import numpy as np


arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

new_arr = np.power(arr1,arr2)

print(new_arr)

[           1000         3200000 590490000000000   6553600000000
            2500               0]


#### Remaider

In [40]:
import numpy as np


arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

new_arr = np.mod(arr1, arr2)

print("Remainder: ",new_arr)


print("\n---------------------------------------------------\n")

new_arr2 = np.remainder(arr1,arr2)

print("Remainder: ",new_arr2)

Remainder:  [ 1  0  0  0  0 27]

---------------------------------------------------

Remainder:  [ 1  0  0  0  0 27]


#### Quotient and Mod

In [34]:
import numpy as np


arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

new_arr = np.divmod(arr1, arr2)

print(new_arr)

(array([ 3,  4,  3,  5, 25,  1]), array([ 1,  0,  0,  0,  0, 27]))


#### Absolute values

In [38]:
import numpy as np

arr = np.array([2,-1,-5,4,-5,9])

new_arr = np.absolute(arr)

print("Absolute array:",new_arr)

print("\n----------------------------------------\n")

print("With abs:",np.abs(arr))

Absolute array: [2 1 5 4 5 9]

----------------------------------------

With abs: [2 1 5 4 5 9]


## 4. Rounding decimals

#### truncation

In [48]:
import numpy as np

arr = np.trunc([1.22222,3,-0.71,0.7,3.4])

print("Rounded values: ",arr)

print(arr.dtype)

Rounded values:  [ 1.  3. -0.  0.  3.]
float64


#### fix

In [49]:
import numpy as np

arr = np.trunc([1.22222, 3, -0.71, 0.7, 3.4])

print(arr)
print(arr.dtype)

[ 1.  3. -0.  0.  3.]
float64


#### Rounding

In [70]:
import numpy as np

arr = np.array([1.22222, 3, -0.71, 0.7, 3.4])

new_arr = np.around(arr,1)

print(new_arr)

print("\n----------------------------------------\n")

new_arr = np.around(arr, 0)

print(new_arr)

[ 1.2  3.  -0.7  0.7  3.4]

----------------------------------------

[ 1.  3. -1.  1.  3.]


#### floor

In [64]:
import numpy as np

arr = np.floor([1.22222, 3, -0.71, 0.7, 3.4])


print(arr)

[ 1.  3. -1.  0.  3.]


#### celi

In [65]:
import numpy as np

arr = np.ceil([1.22222, 3, -0.71, 0.7, 3.4])


print(arr)

[ 2.  3. -0.  1.  4.]


## 5. NumPy Logs

#### Log at base 2

In [ ]:
import numpy as np

arr = np.arange(1,10)
print(arr)

print("\n------------------------------\n")

print(np.log2(arr))


[1 2 3 4 5 6 7 8 9]

------------------------------

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


#### Log at base 10


In [75]:
import numpy as np

arr = np.arange(1,10)
print(arr)

print("\n------------------------------\n")

print(np.log10(arr))

[1 2 3 4 5 6 7 8 9]

------------------------------

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


#### Natural log (base e)

In [77]:
import numpy as np

arr = np.arange(1,10)
print(arr)

print("\n------------------------------\n")

print(np.log(arr))

[1 2 3 4 5 6 7 8 9]

------------------------------

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


#### log at any base

In [80]:
from math import log
import numpy as np

nplog = np.frompyfunc(log,2,1)

print(nplog(100,15))

1.7005483074552052


## 6. Summations

#### Difference of addition and summation

In [ ]:


import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

new_arr = np.add(arr1,arr2)

print(f"Addittion: {new_arr}")

new_arr = np.sum([arr1,arr2])
print(f"Summation : {new_arr}")

Addittion: [2 4 6]
Summation : 12


In [107]:
import numpy as np

arr = np.array([5,6,7,8])

new_arr = np.sum(arr)
print("Summation: ",new_arr)

Summation:  26


#### Summation over an axis

In [89]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([1,4,3])

new_arr = np.sum([arr1, arr2],axis=1)
print(f"with axis = 1 : {new_arr}")

new_arr = np.sum([arr1, arr2], axis=0)
print(f"With axis = 0 : {new_arr}")

with axis = 1 : [6 8]
With axis = 0 : [2 6 6]


#### Cummulative sum

In [93]:
import numpy as np

arr = np.arange(1,10)
print(arr)

new_arr = np.cumsum(arr)

print(f"Cummulative sum: {new_arr}")

[1 2 3 4 5 6 7 8 9]
Cummulative sum: [ 1  3  6 10 15 21 28 36 45]


## 7. NumPy products

In [94]:
import numpy as np

arr = np.arange(1,10)
print(arr)

new_arr = np.prod(arr)

print(f"Product array: {new_arr}")

[1 2 3 4 5 6 7 8 9]
Product array: 362880


#### Product of the elment of two arrays

In [100]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

new_arr = np.prod([arr1,arr2])
print(f"without axis: {new_arr}")

new_arr = np.prod([arr1, arr2], axis=0)
print(f"with axis = 0: {new_arr}")

new_arr = np.prod([arr1, arr2], axis=1)
print(f"with axis = 1: {new_arr}")

without axis: 40320
with axis = 0: [ 5 12 21 32]
with axis = 1: [  24 1680]


#### Cummulative product

In [103]:
import numpy as np

arr = np.array([5,6,7,8])

new_arr = np.cumprod(arr)

print("Cumulative product: ",new_arr)

Cumulative product:  [   5   30  210 1680]


## 8. NumPy differences

In [108]:
import numpy as np

arr = np.array([10,20,15,1])

new_arr = np.diff(arr)

print("Difference: ",new_arr)

Difference:  [ 10  -5 -14]


#### compute difference multiple times

In [ ]:
import numpy as np

arr = np.array([10, 20, 15, 1])

new_arr = np.diff(arr,n=1)   #By default n=1
print(f"Difference once: {new_arr}")

new_arr = np.diff(arr,n=2)
print(f"Difference twice: {new_arr}")

new_arr = np.diff(arr,n=3)
print(f"Difference thrice: {new_arr}")


print("\n--------------------------------------------\n")
new_arr = np.diff(arr)
new_arr = np.diff(new_arr)
print(f"difference by running 2 times np.diff(): {new_arr}")

Difference once: [ 10  -5 -14]
Difference twice: [-15  -9]
Difference thrice: [6]

--------------------------------------------

difference by running 2 times np.diff: [-15  -9]


## 9. Finding LCM

In [ ]:
import numpy as np

num1 = 6
num2 = 10

lcm = np.lcm(num1,num2)

print(lcm)

30


#### lcm of an array

In [126]:
import numpy as np

arr = np.arange(1,7)
print(arr)

lcm = np.lcm.reduce(arr)

print("lcm: ",lcm)

[1 2 3 4 5 6]
lcm:  60


## 10. GCD

In [131]:
import numpy as np

num1 = 10
num2 = 5

gcd = np.gcd(num1,num2)

print(f"GCD of {num1} and {num2} is: {gcd}")

GCD of 10 and 5 is: 5


#### gcd in arrays

In [133]:
import numpy as np

arr = np.array([12,20,32])

gcd = np.gcd.reduce(arr)

print(f"gcd of {arr} is: {gcd}")

gcd of [12 20 32] is: 4


## 11. NumPy Trignometric Functions

In [135]:
import numpy as np

res = np.sin(np.pi/2)

print(res)

1.0


In [141]:
import numpy as np

arr = np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])

res = np.sin(arr)

print(res)

[1.         0.8660254  0.70710678 0.58778525]


#### Convert degreee into radians

In [143]:
import numpy as np

arr = np.array([90,180,270,360])

res = np.deg2rad(arr)

print("Converted value: ",res)

Converted value:  [1.57079633 3.14159265 4.71238898 6.28318531]


#### Convert raidan to degree

In [144]:
import numpy as np

arr = np.array([np.pi,np.pi/2,2*np.pi])

res = np.rad2deg(arr)

print(res)

[180.  90. 360.]


#### Finding angles

In [160]:
import numpy as np

res = np.arcsin(1.0)

print("Angle: ",res)

print("In degree: ",np.rad2deg(res))

Angle:  1.5707963267948966
In degree:  90.0


#### Hypotenues

In [156]:
import numpy as np

base = 4
perp = 5

hypot = np.hypot(base,perp)

print(hypot)

6.4031242374328485


## 12. Hyperbolic functions

In [157]:
import numpy as np

res = np.sinh(np.pi/2)

print(res)

2.3012989023072947


In [158]:
import numpy as np

arr = np.array([np.pi, np.pi / 2, 2 * np.pi])

res = np.cosh(arr)

print(res)

[ 11.59195328   2.50917848 267.74676148]


#### finding angle

In [161]:
import numpy as np

res = np.arcsinh(0.1)

print(res)

0.09983407889920756


#### Angle of each value in array

In [162]:
import numpy as np

arr = np.array([0.1,0.2,0.5])

res = np.arctanh(arr)

print(res)

[0.10033535 0.20273255 0.54930614]


## 13. Set operations

In [164]:
import numpy as np

arr = np.array([1,2,1,5,5,3,4,7])

res = np.unique(arr)

print('Set: ',res)  #It will only contain unique elements

Set:  [1 2 3 4 5 7]


#### Union

In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([1,6,2,3,6,4])

new_arr = np.union1d(arr1,arr2)

print('Union: ',new_arr)

Union:  [1 2 3 4 6]


#### Intersection

In [166]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 6, 2, 3, 6, 4])

new_arr = np.intersect1d(arr1, arr2)

print("Intersection: ", new_arr)

Intersection:  [1 2 3 4]


### Defference

In [172]:
import numpy as np

arr1 = np.array([1, 2, 3, 4,5])
arr2 = np.array([1, 6, 2, 3, 6, 4,8])

new_arr = np.setdiff1d(arr1, arr2)

print("difference: ", new_arr)

print("\n-----------------------------------------\n")

new_arr = np.setdiff1d(arr2, arr1)

print("difference: ", new_arr)

difference:  [5]

-----------------------------------------

difference:  [6 8]


#### Finding symmatric Difference

In [178]:
import numpy as np

set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([1, 6, 2, 3, 6, 4, 8])


new_arr = np.setxor1d(set1,set2)

print(new_arr)

[5 6 8]


In [179]:
import numpy as np

set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([1, 6, 2, 3, 6, 4, 8])


new_arr = np.setxor1d(set1, set2,assume_unique=True)

print(new_arr)

[5 8]
