## 1. Checking NumPy version

In [3]:
import numpy as np
print(np.__version__)

2.1.3


## 2. Creating NumPy array 

In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 3. Creating 2D array

In [7]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## 4. Creating 3D array

In [10]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## 5. Check number of dimensions

In [6]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])



print(a,f"dimension: {a.ndim}\n--------------")
print(b,f"dimension: {b.ndim}\n--------------")
print(c,f"dimension: {c.ndim}\n--------------")
print(d,f"dimension: {d.ndim}")


42 dimension: 0
--------------
[1 2 3 4 5] dimension: 1
--------------
[[1 2 3 4]
 [5 6 7 8]] dimension: 2
--------------
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] dimension: 3


## 6. Higher Dimensional arrays

In [12]:
import numpy as np

arr = np.array([1,2,3,4],ndmin = 5)

print(arr)
print(f"Number of dimensions: {arr.ndim}")

[[[[[1 2 3 4]]]]]
Number of dimensions: 5


## 7. Acess array elements

In [22]:
import numpy as np

arr = np.array([1,2,3,4])

print("first elment: ",arr[0])

print("second element: ",arr[1])


first elment:  1
second element:  2


## 8. Access 2D arrays

In [29]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

print("Second element on 1st row: ",arr[0,1])

print("3rd element on 2nd row: ",arr[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Second element on 1st row:  2
3rd element on 2nd row:  8


## 9. Access 3D arrays

In [38]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr,"\n------------------")
print(arr[1,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
------------------
9


## 10. Negative indexing

In [3]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr,end="\n--------------------------------\n")

print("second last elment in second row: ",arr[1,-2])

[[1 2 3 4]
 [5 6 7 8]]
--------------------------------
second last elment in second row:  7


## 11. NumPy array slicing

In [6]:
import numpy as np

arr = np.array([i for i in range(10)])

print(arr,end="\n----------------------------------\n")
print(" array with element from 2nd to 5th: ",arr[1:5])

[0 1 2 3 4 5 6 7 8 9]
----------------------------------
 array with element from 2nd to 5th:  [1 2 3 4]


In [ ]:
import numpy as np

arr = np.array([i for i in range(10)])

print("actual array: ",arr)

print("Element from 4th :",arr[3:]) 

actual array:  [0 1 2 3 4 5 6 7 8 9]
Element from 4th : [3 4 5 6 7 8 9]


In [13]:
import numpy as np

arr = np.array([i for i in range(10)])

print("Actual array: ",arr)
print("Element upto 4: ",arr[:5])

Actual array:  [0 1 2 3 4 5 6 7 8 9]
Element upto 4:  [0 1 2 3 4]


In [17]:
#negative slicing

import numpy as np

arr = np.array([i for i in range(10)])

print("Actual array: ",arr)

print("Element from 7th to 9th: ",arr[-4:-1])  #negative index start from -1

Actual array:  [0 1 2 3 4 5 6 7 8 9]
Element from 7th to 9th:  [6 7 8]


## 12. 2D array slicing

In [20]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(f"Actual array:\n {arr}",end="\n--------------------------\n")
print(f"element from 5 to 6 (2nd row last two): {arr[1,1:]}")

Actual array:
 [[1 2 3]
 [4 5 6]]
--------------------------
element from 5 to 6 (2nd row last two): [5 6]


In [25]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(f"Actual array: \n {arr}")
print(f"second element in both the row: {arr[0:2,1]}")



Actual array: 
 [[1 2 3 4]
 [5 6 7 8]]
second element in both the row: [2 6]


In [30]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(f"Actual array:\n {arr}")

print(f" 2nd to 4th element in both the row:\n {arr[0:2,1:4]}")

Actual array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
 2nd to 4th element in both the row:
 [[2 3 4]
 [7 8 9]]


## -> np Array  vs list : time comparision

In [38]:
import time

start = time.time()

a = [i for i in range(10000000)]
b = [i for i in range(1000000,200000000)]

print(time.time() - start)

4.4173829555511475


In [39]:

start = time.time()

a = np.arange(10000000)
b = np.arange(1000000,200000000)

print(time.time() - start)

2.113945245742798


## 13. Data types in numpy

In [5]:
import numpy as np

arr = np.array([1,2,3,4])
print(f"data type of {arr}: ",arr.dtype)

arr = np.array(["kannur","kozikode","malapuram"])
print(f"data type of {arr} : {arr.dtype}")

data type of [1 2 3 4]:  int64
data type of ['kannur' 'kozikode' 'malapuram'] : <U9


## 14. Creating array with defined data type

In [6]:
import numpy as np
arr = np.array([1,2,3],dtype='S')

print(f"array {arr}: data type :{arr.dtype}")

array [b'1' b'2' b'3']: data type :|S1


In [35]:
import numpy as np

dtype_list = {'integer':'i','boolean':'?','unsigned integer':'u','float':'f','complex float':'c','timedelta':'m','date time':'M','Object':'O','string':'S','unicode string':'U','fixed chunck of memory for other type(void)':'V'}



for datatype,character in dtype_list.items():
  try:
    arr = np.array([0,1,2,3,4,5],dtype=character)
    print(f"{datatype} array: {arr} : data type: {arr.dtype}",end="\n------------------------------------\n\n")
  except:
    print(f"{datatype} is not possible on array {arr}",end="\n------------------------------------\n\n")
  

integer array: [0 1 2 3 4 5] : data type: int32
------------------------------------

boolean array: [False  True  True  True  True  True] : data type: bool
------------------------------------

unsigned integer is not possible on array [False  True  True  True  True  True]
------------------------------------

float array: [0. 1. 2. 3. 4. 5.] : data type: float32
------------------------------------

complex float array: [b'0' b'1' b'2' b'3' b'4' b'5'] : data type: |S1
------------------------------------

timedelta array: [0 1 2 3 4 5] : data type: timedelta64
------------------------------------

date time is not possible on array [0 1 2 3 4 5]
------------------------------------

Object array: [0 1 2 3 4 5] : data type: object
------------------------------------

string array: [b'0' b'1' b'2' b'3' b'4' b'5'] : data type: |S1
------------------------------------

unicode string array: ['0' '1' '2' '3' '4' '5'] : data type: <U1
------------------------------------

fixed chunck of 

In [37]:
import numpy as np

arr = np.array([1.1,2.1,3.1],dtype='i')

print(arr)

[1 2 3]


In [40]:
#Fixed length

import numpy as np

arr = np.array(['apple','banana','cherry'],dtype='S2')

print(arr)

[b'ap' b'ba' b'ch']


## 15. Converting datatype

In [51]:
import numpy as np

arr = np.array([1.1,2.1,3.2])

newarr = arr.astype('i')

print(f"old array: {arr}, new arr: {newarr}")

print("--------------------------------------------")

print(f"converting to boolean:\n array: {arr} : new array: {arr.astype('?')}")

old array: [1.1 2.1 3.2], new arr: [1 2 3]
--------------------------------------------
converting to boolean:
 array: [1.1 2.1 3.2] : new array: [ True  True  True]


## 16. Numpy array copy

In [53]:
import numpy as np

arr = np.array([1,2,3])
new_arr = arr.copy()

print(f"Old array: {arr}, new array: {new_arr}")

arr[2] = 1

print(f"Old array: {arr}, new array: {new_arr}")

Old array: [1 2 3], new array: [1 2 3]
Old array: [1 2 1], new array: [1 2 3]


## 17. Numpy array view

In [55]:
import numpy as np

arr = np.array([1,2,3,4])
new_arr = arr.view()


print(f"Old array: {arr}, new array: {new_arr}")

arr[2] = 10


print(f"Old array: {arr}, new array: {new_arr}")

Old array: [1 2 3 4], new array: [1 2 3 4]
Old array: [ 1  2 10  4], new array: [ 1  2 10  4]


array([ 1,  2, 10,  4])