## 1. Checking NumPy version

In [3]:
import numpy as np
print(np.__version__)

2.1.3


## 2. Creating NumPy array 

In [5]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 3. Creating 2D array

In [7]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


## 4. Creating 3D array

In [10]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## 5. Check number of dimensions

In [6]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])



print(a,f"dimension: {a.ndim}\n--------------")
print(b,f"dimension: {b.ndim}\n--------------")
print(c,f"dimension: {c.ndim}\n--------------")
print(d,f"dimension: {d.ndim}")


42 dimension: 0
--------------
[1 2 3 4 5] dimension: 1
--------------
[[1 2 3 4]
 [5 6 7 8]] dimension: 2
--------------
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] dimension: 3


## 6. Higher Dimensional arrays

In [12]:
import numpy as np

arr = np.array([1,2,3,4],ndmin = 5)

print(arr)
print(f"Number of dimensions: {arr.ndim}")

[[[[[1 2 3 4]]]]]
Number of dimensions: 5


## 7. Acess array elements

In [22]:
import numpy as np

arr = np.array([1,2,3,4])

print("first elment: ",arr[0])

print("second element: ",arr[1])


first elment:  1
second element:  2


## 8. Access 2D arrays

In [29]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

print("Second element on 1st row: ",arr[0,1])

print("3rd element on 2nd row: ",arr[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Second element on 1st row:  2
3rd element on 2nd row:  8


## 9. Access 3D arrays

In [38]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr,"\n------------------")
print(arr[1,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
------------------
9


## 10. Negative indexing

In [3]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr,end="\n--------------------------------\n")

print("second last elment in second row: ",arr[1,-2])

[[1 2 3 4]
 [5 6 7 8]]
--------------------------------
second last elment in second row:  7


## 11. NumPy array slicing

In [6]:
import numpy as np

arr = np.array([i for i in range(10)])

print(arr,end="\n----------------------------------\n")
print(" array with element from 2nd to 5th: ",arr[1:5])

[0 1 2 3 4 5 6 7 8 9]
----------------------------------
 array with element from 2nd to 5th:  [1 2 3 4]


In [ ]:
import numpy as np

arr = np.array([i for i in range(10)])

print("actual array: ",arr)

print("Element from 4th :",arr[3:]) 

actual array:  [0 1 2 3 4 5 6 7 8 9]
Element from 4th : [3 4 5 6 7 8 9]


In [13]:
import numpy as np

arr = np.array([i for i in range(10)])

print("Actual array: ",arr)
print("Element upto 4: ",arr[:5])

Actual array:  [0 1 2 3 4 5 6 7 8 9]
Element upto 4:  [0 1 2 3 4]


In [17]:
#negative slicing

import numpy as np

arr = np.array([i for i in range(10)])

print("Actual array: ",arr)

print("Element from 7th to 9th: ",arr[-4:-1])  #negative index start from -1

Actual array:  [0 1 2 3 4 5 6 7 8 9]
Element from 7th to 9th:  [6 7 8]


## 12. 2D array slicing

In [20]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(f"Actual array:\n {arr}",end="\n--------------------------\n")
print(f"element from 5 to 6 (2nd row last two): {arr[1,1:]}")

Actual array:
 [[1 2 3]
 [4 5 6]]
--------------------------
element from 5 to 6 (2nd row last two): [5 6]


In [25]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(f"Actual array: \n {arr}")
print(f"second element in both the row: {arr[0:2,1]}")



Actual array: 
 [[1 2 3 4]
 [5 6 7 8]]
second element in both the row: [2 6]


In [30]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(f"Actual array:\n {arr}")

print(f" 2nd to 4th element in both the row:\n {arr[0:2,1:4]}")

Actual array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
 2nd to 4th element in both the row:
 [[2 3 4]
 [7 8 9]]


#### -> np Array  vs list : time comparision

In [38]:
import time

start = time.time()

a = [i for i in range(10000000)]
b = [i for i in range(1000000,200000000)]

print(time.time() - start)

4.4173829555511475


In [39]:

start = time.time()

a = np.arange(10000000)
b = np.arange(1000000,200000000)

print(time.time() - start)

2.113945245742798


## 13. Data types in numpy

In [5]:
import numpy as np

arr = np.array([1,2,3,4])
print(f"data type of {arr}: ",arr.dtype)

arr = np.array(["kannur","kozikode","malapuram"])
print(f"data type of {arr} : {arr.dtype}")

data type of [1 2 3 4]:  int64
data type of ['kannur' 'kozikode' 'malapuram'] : <U9


## 14. Creating array with defined data type

In [6]:
import numpy as np
arr = np.array([1,2,3],dtype='S')

print(f"array {arr}: data type :{arr.dtype}")

array [b'1' b'2' b'3']: data type :|S1


In [35]:
import numpy as np

dtype_list = {'integer':'i','boolean':'?','unsigned integer':'u','float':'f','complex float':'c','timedelta':'m','date time':'M','Object':'O','string':'S','unicode string':'U','fixed chunck of memory for other type(void)':'V'}



for datatype,character in dtype_list.items():
  try:
    arr = np.array([0,1,2,3,4,5],dtype=character)
    print(f"{datatype} array: {arr} : data type: {arr.dtype}",end="\n------------------------------------\n\n")
  except:
    print(f"{datatype} is not possible on array {arr}",end="\n------------------------------------\n\n")
  

integer array: [0 1 2 3 4 5] : data type: int32
------------------------------------

boolean array: [False  True  True  True  True  True] : data type: bool
------------------------------------

unsigned integer is not possible on array [False  True  True  True  True  True]
------------------------------------

float array: [0. 1. 2. 3. 4. 5.] : data type: float32
------------------------------------

complex float array: [b'0' b'1' b'2' b'3' b'4' b'5'] : data type: |S1
------------------------------------

timedelta array: [0 1 2 3 4 5] : data type: timedelta64
------------------------------------

date time is not possible on array [0 1 2 3 4 5]
------------------------------------

Object array: [0 1 2 3 4 5] : data type: object
------------------------------------

string array: [b'0' b'1' b'2' b'3' b'4' b'5'] : data type: |S1
------------------------------------

unicode string array: ['0' '1' '2' '3' '4' '5'] : data type: <U1
------------------------------------

fixed chunck of 

In [37]:
import numpy as np

arr = np.array([1.1,2.1,3.1],dtype='i')

print(arr)

[1 2 3]


In [40]:
#Fixed length

import numpy as np

arr = np.array(['apple','banana','cherry'],dtype='S2')

print(arr)

[b'ap' b'ba' b'ch']


## 15. Converting datatype

In [51]:
import numpy as np

arr = np.array([1.1,2.1,3.2])

newarr = arr.astype('i')

print(f"old array: {arr}, new arr: {newarr}")

print("--------------------------------------------")

print(f"converting to boolean:\n array: {arr} : new array: {arr.astype('?')}")

old array: [1.1 2.1 3.2], new arr: [1 2 3]
--------------------------------------------
converting to boolean:
 array: [1.1 2.1 3.2] : new array: [ True  True  True]


## 16. Numpy array copy

In [53]:
import numpy as np

arr = np.array([1,2,3])
new_arr = arr.copy()

print(f"Old array: {arr}, new array: {new_arr}")

arr[2] = 1

print(f"Old array: {arr}, new array: {new_arr}")

Old array: [1 2 3], new array: [1 2 3]
Old array: [1 2 1], new array: [1 2 3]


## 17. Numpy array view

In [55]:
import numpy as np

arr = np.array([1,2,3,4])
new_arr = arr.view()


print(f"Old array: {arr}, new array: {new_arr}")

arr[2] = 10


print(f"Old array: {arr}, new array: {new_arr}")

Old array: [1 2 3 4], new array: [1 2 3 4]
Old array: [ 1  2 10  4], new array: [ 1  2 10  4]


## 18. check if array owns its data

In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4])
new_arrview = arr.view()
new_arrcopy = arr.copy()


print(new_arrview.base)
print(new_arrcopy.base)  #None means it owns

[1 2 3 4]
None


## 19. Get the shape of an array

In [63]:
import numpy as np

arr = np.array([1,2,3,4])
print(f"array: {arr}, shape: {arr.shape}\n")

arr = np.array([[1,2,3],[4,5,6]])
print(f"array:\n {arr}, shape: {arr.shape}\n")

arr = np.array([1,2,3,4,5],ndmin=5)
print(f"array: {arr}, shape: {arr.shape}")

array: [1 2 3 4], shape: (4,)

array:
 [[1 2 3]
 [4 5 6]], shape: (2, 3)

array: [[[[[1 2 3 4 5]]]]], shape: (1, 1, 1, 1, 5)


## 20. NumPy array reshape


In [71]:
import numpy as np

arr = np.array([i for i in range(1,11)])
print(arr)

new_arr = arr.reshape(2,5)
print(f"array with shape 2 rows and 3 columns :\n {new_arr}")

[ 1  2  3  4  5  6  7  8  9 10]
array with shape 2 rows and 3 columns :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [77]:
import numpy as np

arr = np.array([i for i in range(1, 11)])
print(arr)

try:
  new_arr = arr.reshape(3, 3)
  print(new_arr)
except:
  print("(3,3) shape is not possible for the above array")

[ 1  2  3  4  5  6  7  8  9 10]
(3,3) shape is not possible for the above array


In [96]:
import numpy as np

arr = np.array([i for i in range(1,17)])
print(f"array: {arr}")

new_arr = arr.reshape(2,4,2)
print(f"reshaped 3D array: \n{new_arr}")
print("-----------------------------------------------------------")
print("returing view:",new_arr.base)

array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
reshaped 3D array: 
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
-----------------------------------------------------------
returing view: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [97]:
import numpy as np

arr = np.array([i for i in range(1, 11)])
print(arr)

print("--------------------------")

new_arr = arr.reshape(2, 5)
print(f"array with shape 2 rows and 3 columns :\n {new_arr}")

[ 1  2  3  4  5  6  7  8  9 10]
--------------------------
array with shape 2 rows and 3 columns :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## 21. unknown dimension

In [111]:
import numpy as np

arr = np.array([i for i in range(1,19)])
print(arr)

print("--------------------------")

new_arr = arr.reshape(3,-1,3)
print("reshaped array:\n",new_arr)
print("shape: ",new_arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
--------------------------
reshaped array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
shape:  (3, 2, 3)


In [117]:
import numpy as np

arr = np.array([i for i in range(1, 19)])
print(arr)

print("--------------------------")

try:
  new_arr = arr.reshape(3, -1, -1)
  print("reshaped array:\n", new_arr)
  print("shape: ", new_arr.shape)
except:
  print("only specity one unknown dimension")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
--------------------------
only specity one unknown dimension


## 22. Flattening the arrays

In [123]:
import numpy as np

arr = np.array([i for i in range(1,11)]).reshape(2,5)
print("array: \n",arr)

new_arr = arr.reshape(-1)
print("Flatten array",new_arr)


array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Flatten array [ 1  2  3  4  5  6  7  8  9 10]


## 23. NumPy array iterating

In [125]:
import numpy as np

arr = np.array([i for i in range(10)])

for i in arr:
  print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [126]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for i in arr:
  print(i)

[1 2 3]
[4 5 6]


In [127]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for i in arr:
  for j in i:
    print(j,end=" ")

1 2 3 4 5 6 

In [133]:
import numpy as np

arr = np.array([i for i in range(1,9)]).reshape(2,2,-1)
print("Array:\n",arr)

print("----------------------------")

for i in arr:
  for j in i:
    for k in j:
      print(k,end=" ")


Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
----------------------------
1 2 3 4 5 6 7 8 

## 24. Iterating array uisng nditer()

In [136]:
import numpy as np

arr = np.array([i for i in range(1, 9)]).reshape(2, 2, -1)
print("Array:\n", arr)

print("------------------------------")

for i in np.nditer(arr):
  print(i,end=" ")

Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------------------------------
1 2 3 4 5 6 7 8 

#### -> time comparison of nditer and basic for

In [216]:
import time
start = time.time()

import numpy as np

arr = np.arange(100).reshape(2, 2, -1)
print("Array:\n", arr)

print("----------------------------")

for i in arr:
    for j in i:
        for k in j:
            print(k, end=" ")
            

print("\nTotal time taken: ",(time.time()-start))

Array:
 [[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23 24]
  [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
   48 49]]

 [[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
   73 74]
  [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
   98 99]]]
----------------------------
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 
Total time taken:  0.0007419586181640625


In [217]:
import time

start = time.time()

import numpy as np

arr = np.arange(100).reshape(2, 2, -1)
print("Array:\n", arr)

print("----------------------------")

for i in np.nditer(arr):
    
  print(i, end=" ")

print("\nTotal time taken: ", (time.time() - start))

Array:
 [[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23 24]
  [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
   48 49]]

 [[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
   73 74]
  [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
   98 99]]]
----------------------------
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 
Total time taken:  0.0008029937744140625


## 25. Iterating array with different data types

In [44]:
import numpy as np

arr = np.array([1,0,False,1,0])


for i in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
  print(i)



np.bytes_(b'1')
np.bytes_(b'0')
np.bytes_(b'0')
np.bytes_(b'1')
np.bytes_(b'0')


## 26. Iterating with different step size

In [47]:
import numpy as np

arr = np.arange(1,11).reshape(2,5)
print(arr)

print("------------------------")

for i in np.nditer(arr[:,::2]):
  print(i, end=" ")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
------------------------
1 3 5 6 8 10 

In [54]:
import numpy as np

arr = np.arange(1, 11).reshape(5,2)
print(arr)

print("------------------------")

for i in np.nditer(arr[::2, :]):
    print(i, end=" ")

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
------------------------
1 2 5 6 9 10 

In [55]:
import numpy as np

arr = np.array([1,2,3,4,5])

for index,val in np.ndenumerate(arr):
  print(f"Index: {index}, value: {val}")

Index: (0,), value: 1
Index: (1,), value: 2
Index: (2,), value: 3
Index: (3,), value: 4
Index: (4,), value: 5


In [59]:
import numpy as np

arr = np.array([[1, 2],[ 3, 4],[5,6]])

for index, val in np.ndenumerate(arr):
    print(f"Index: {index}, value: {val}")

Index: (0, 0), value: 1
Index: (0, 1), value: 2
Index: (1, 0), value: 3
Index: (1, 1), value: 4
Index: (2, 0), value: 5
Index: (2, 1), value: 6


## 27. NumPy joining array

In [95]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])

new_arr = np.concatenate((arr1,arr2,arr3))

print("concatenated array: ",new_arr)


concatenated array:  [1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5, 6], [7, 8]])

new_arr = np.concatenate((arr1,arr2)) #by default axis is 0
print("row wise :\n",new_arr)

new_arr = np.concatenate((arr1,arr2),axis=1)
print("column wise: \n",new_arr)

row wise :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
column wise: 
 [[1 2 5 6]
 [3 4 7 8]]


In [84]:
import numpy as np

arr1 = np.array([[[1, 2],[3,4]], [[5,6],[7, 8]]])
arr2 = np.array([[[9, 10],[11,12]],[[13,14],[15, 16]]])

new_arr = np.concatenate((arr1, arr2))  
print("default(axis =0) :\n", new_arr)

print("-------------------")

new_arr = np.concatenate((arr1, arr2),axis=1)
print("axis=1 :\n", new_arr)

print("-------------------")

new_arr = np.concatenate((arr1, arr2))
print("axis = 2 :\n", new_arr)

default(axis =0) :
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
-------------------
axis=1 :
 [[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]
-------------------
axis = 2 :
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


## 28. joining arrays using stack functions

In [93]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1,arr2))
print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
# stack along rows

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# stack along columns

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [97]:
# stack along height

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

marr = np.hstack((arr1, arr2))
print("hstack:\n ",arr)

print("-----------------------")

arr = np.vstack((arr1, arr2))
print("vstack:\n ", arr)

print("-----------------------")

arr = np.dstack((arr1, arr2))
print("dstack:\n ", arr)

hstack:
  [[1 2 5 6]
 [3 4 7 8]]
-----------------------
vstack:
  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
-----------------------
dstack:
  [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## 30. NumPy array splitting

In [109]:
import numpy as n

arr = np.array([1,2,3,4,5,6,7])

new_arr = np.array_split(arr,3)
print(f"splitted array: {new_arr}")

splitted array: [array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [ ]:
import numpy as n

arr = np.array([1, 2, 3])

new_arr = np.array_split(arr, 5)  
print(f"splitted array: {new_arr}")

splitted array: [array([1]), array([2]), array([3]), array([], dtype=int64), array([], dtype=int64)]


In [110]:
import numpy as n

arr = np.array([1, 2, 3, 4, 5, 6, 7])

new_arr = np.array_split(arr, 3)
print(f"splitted array: {new_arr}")

print(f"first array: {new_arr[0]}")
print(f"second array: {new_arr[1]}")
print(f"third array: {new_arr[2]}")

splitted array: [array([1, 2, 3]), array([4, 5]), array([6, 7])]
first array: [1 2 3]
second array: [4 5]
third array: [6 7]


In [115]:
#Splitting 2d array

import numpy as np

arr = np.arange(1,11).reshape(5,2)
print(f"array: \n{arr}")

print("-----------------------------------")

new_arr = np.array_split(arr,5)
print(f"splitted arrray: \n{new_arr}")

array: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
-----------------------------------
splitted arrray: 
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]])]


In [122]:
# Splitting 2d array

import numpy as np

arr = np.arange(1, 16).reshape(3, 5)
print(f"array: \n{arr}")

print("-----------------------------------")

new_arr = np.array_split(arr,5,axis=1)
print(f"splitted arrray: \n{new_arr}")

array: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-----------------------------------
splitted arrray: 
[array([[ 1],
       [ 6],
       [11]]), array([[ 2],
       [ 7],
       [12]]), array([[ 3],
       [ 8],
       [13]]), array([[ 4],
       [ 9],
       [14]]), array([[ 5],
       [10],
       [15]])]


In [127]:
# Splitting 2d array

import numpy as np

arr = np.arange(1, 11).reshape(5, 2)
print(f"array: \n{arr}")

print("-----------------------------------")

new_arr = np.hsplit(arr,2)
print(f"splitted arrray-hsplit: \n{new_arr}")

array: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
-----------------------------------
splitted arrray-hsplit: 
[array([[1],
       [3],
       [5],
       [7],
       [9]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])]


In [132]:
# Splitting 2d array

import numpy as np

arr = np.arange(1, 11).reshape(5, 2)
print(f"array: \n{arr}")

print("-----------------------------------")

new_arr = np.vsplit(arr, 5)
print(f"splitted arrray-vsplit: \n{new_arr}")

array: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
-----------------------------------
splitted arrray-vsplit: 
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]])]


In [143]:
# Splitting 2d array

import numpy as np

arr = np.arange(1, 11).reshape(5, 2)
print(f"array: \n{arr}")

print("-----------------------------------")

try:
  new_arr = np.dsplit(arr, 2)
  print(f"splitted arrray-hdsplit: \n{new_arr}")
except:
  print("dsplit is only possible on array of 3 dimension or above")

array: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
-----------------------------------
dsplit is only possible on array of 3 dimension or above


In [ ]:
# Splitting 2d array

import numpy as np

arr = np.arange(1, 19).reshape(3, 2,3)
print(f"array: \n{arr}")

print("-----------------------------------")

new_arr = np.dsplit(arr, 3)
print(f"splitted arrray-vsplit: \n{new_arr}")

array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
-----------------------------------
splitted arrray-vsplit: 
[array([[[ 1],
        [ 4]],

       [[ 7],
        [10]],

       [[13],
        [16]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]],

       [[14],
        [17]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]],

       [[15],
        [18]]])]


## 31. Array searching

In [146]:
import  numpy as np

arr = np.array([1,2,3,4])

index_val = np.where(arr==3)

print(f"Index of value 3: {index_val}")

Index of value 3: (array([2]),)


In [149]:
#Find odd numbers- odd numbers are at even index

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

odd_nums = np.where(arr%2 == 0)

print(odd_nums)

(array([1, 3, 5, 7]),)


In [150]:
#find even numbers

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

even_nums = np.where(arr%2==1)

print(even_nums)

(array([0, 2, 4, 6]),)


## 32. Search sorted

In [166]:
import numpy as np

arr = np.array([6,7,8,9])

new_arr = np.searchsorted(arr,7)

print(new_arr)

1


In [177]:
import numpy as np

arr = np.array([1,3,6,10])

position = np.searchsorted(arr, 2)
print(f"Position where 2 shuld be inserted: {position}")

position = np.searchsorted(arr, 9)
print(f"Position where 9 shuld be inserted: {position}")

position = np.searchsorted(arr, 4)
print(f"Position where 4 shuld be inserted: {position}")

Position where 2 shuld be inserted: 1
Position where 9 shuld be inserted: 3
Position where 4 shuld be inserted: 2


In [189]:
# Search from the right side - It doesnt mean that count from left 
# It actualy means that insert left if that element aldready present in array


arr = np.array([1, 3, 6, 10])

position = np.searchsorted(arr, 3,side='right')
print(f"Position where 2 shuld be inserted (it will give right side of existing 3): {position}")

position = np.searchsorted(arr, 3)
print(f"Position where 3 shuld be inserted( it give left side): {position}")

position = np.searchsorted(arr, 4, side="right")
print(f"Position where 4 shuld be inserted: {position}")

Position where 2 shuld be inserted (it will give right side of existing 3): 2
Position where 3 shuld be inserted( it give left side): 1
Position where 4 shuld be inserted: 2


In [199]:
#Multiple values

import numpy as np

arr = np.array([1,3,5,7,9])

positions = np.searchsorted(arr,[2,6,8])

print(f'position for inserting elements: {2,6,8} in {arr}\n {positions}')

position for inserting elements: (2, 6, 8) in [1 3 5 7 9]
 [1 3 4]


## 33. NumPy array sorting

In [201]:
import numpy as np

arr = np.array([0,5,2,1])

sorted_array = np.sort(arr)

print(f"Sorted array : {sorted_array}")

Sorted array : [0 1 2 5]


In [203]:
# sorting different datatypes

import numpy as np

string_arr = np.array(["banana","cherry","apple"])
print(f"sorted : {np.sort(arr)}")

bool_arr = np.array([True, False, False,True])
print(f"sorted : {np.sort(bool_arr)}")



sorted : [0 1 2 5]
sorted : [False False  True  True]


In [207]:
# sorting 2D array

import numpy as np

arr = np.array([[4,3,6],[8,8,3],[8,2,3]])

print(f"Sorted array:\n {np.sort(arr)}")

Sorted array:
 [[3 4 6]
 [3 8 8]
 [2 3 8]]


In [206]:
# sorting 3D array

import numpy as np

arr = np.array([[[4, 3, 6], [8, 8, 3]], [[8, 2, 3],[4,2,9]]])

print(f"Sorted array:\n {np.sort(arr)}")

Sorted array:
 [[[3 4 6]
  [3 8 8]]

 [[2 3 8]
  [2 4 9]]]


## 34. NumPy filter array

In [209]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

refer_arr = [False, True, True, False, True, False]

new_arr = arr[refer_arr]

print("New array: ",new_arr)

New array:  [2 3 5]


In [212]:
#Creating filter array

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

filter_arr=[]

for elment in arr:
  if elment%2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

print("Filter array: ",filter_arr)
print("Filtered array: ",arr[filter_arr])

Filter array:  [False, True, False, True, False, True, False, True]
Filtered array:  [2 4 6 8]


In [213]:
#creating filter directly from array

import numpy as np

arr = np.array([i for i in range(1,10)])
print(arr)

filter_arr = arr%2 == 0

new_arr = arr[filter_arr]

print("Filter array: ",new_arr)

[1 2 3 4 5 6 7 8 9]
Filter array:  [2 4 6 8]
